[package]
name = "marvyr-playtest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "marvyr_playtest"
path = "src/main.rs"

[dependencies]
marvyr-client = { path = "../../client" }
marvyr-server = { path = "../../server" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
