[package]
name = "mareforge-domain-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mareforge-shared = { path = "../shared" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
bincode = "1"
