[package]
name = "marvyr-domain-combat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
marvyr-domain-items = { path = "../domain-items" }
marvyr-shared = { path = "../shared" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
