[package]
name = "marvyr-domain-crafting"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
marvyr-shared = { path = "../shared" }
marvyr-domain-items = { path = "../domain-items" }
marvyr-domain-ships = { path = "../domain-ships" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
smallvec = "1"
