[package]
name = "mareforge-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mareforge-domain-combat = { path = "../domain-combat" }
mareforge-domain-crafting = { path = "../domain-crafting" }
mareforge-domain-world = { path = "../domain-world" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
bincode = "1"
